# Generated by Django 5.2.12 on 2026-06-03 06:22

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_author_id_alter_blogpagegalleryimage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='article_source',
            field=models.CharField(blank=True, default='新闻网', max_length=100, null=True, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='editor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='编辑'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='reviewer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='审核'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='subtitle',
            field=models.CharField(blank=True, default='这是一个副标题', max_length=255, null=True, verbose_name='副标题'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tiltle',
            field=models.CharField(default='默认标题', max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(verbose_name='正文'),
        ),
    ]
