# Generated by Django 5.2.12 on 2026-06-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpage_authors_remove_blogpage_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='tiltle',
        ),
    ]
