# Generated by Django 5.2.12 on 2026-06-03 12:19

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpage_tiltle'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.author', verbose_name='文章作者'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(blank=True, verbose_name='文章导语'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='reading_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='预计阅读时间'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='分类标签'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='页面简介'),
        ),
        migrations.AlterField(
            model_name='blogpagegalleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=250, verbose_name='图片脚注'),
        ),
    ]
