# Generated by Django 5.2.12 on 2026-03-31 11:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE home_homepage SET body = '[]';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('news', 11), ('media', 16), ('events', 21), ('education', 24), ('research', 29)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2), ('cta_text', 1), ('cta_link', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': '新闻动态'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'NEWS', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {}), 8: ('wagtail.blocks.DateBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('summary', 7), ('date', 8), ('link', 3)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('subtitle', 6), ('news_items', 10), ('view_more_link', 3)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': '媒体报道'}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'MEDIA', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('source', 0), ('title', 0), ('link', 3), ('date', 0)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('subtitle', 13), ('media_items', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': '活动预告'}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'EVENTS', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 7), ('time', 0), ('location', 0)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('title', 17), ('subtitle', 18), ('events', 20), ('view_more_link', 3)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'default': '教育教学'}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'EDUCATION', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('title', 22), ('subtitle', 23), ('content', 7), ('view_more_link', 3)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': '科学研究'}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'RESEARCH', 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 7)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('title', 25), ('subtitle', 26), ('research_items', 28), ('view_more_link', 3)]], {})}),
        ),
    ]
