# Generated by Django 6.0.3 on 2026-04-14 08:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='全局头部背景图'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('news', 12), ('media', 17), ('events', 22), ('education', 25), ('research', 30)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2), ('cta_text', 1), ('cta_link', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': '新闻动态'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'NEWS', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {}), 8: ('wagtail.blocks.DateBlock', (), {}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('summary', 7), ('date', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 5), ('subtitle', 6), ('news_items', 11), ('view_more_link', 9)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': '媒体报道'}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'MEDIA', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('source', 0), ('title', 0), ('link', 9), ('date', 0)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('title', 13), ('subtitle', 14), ('media_items', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': '活动预告'}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'EVENTS', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 7), ('time', 0), ('location', 0)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('title', 18), ('subtitle', 19), ('events', 21), ('view_more_link', 9)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'default': '教育教学'}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'EDUCATION', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('title', 23), ('subtitle', 24), ('content', 7), ('view_more_link', 9)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': '科学研究'}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'RESEARCH', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 7)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {}), 30: ('wagtail.blocks.StructBlock', [[('title', 26), ('subtitle', 27), ('research_items', 29), ('view_more_link', 9)]], {})}),
        ),
    ]
