# Generated by Django 6.0.3 on 2026-04-20 05:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_homepage_hero_cta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 3), ('news', 12), ('media', 17), ('events', 22), ('education', 25), ('research', 30)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '轮播图片', 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': '点击图片后的跳转地址', 'label': '跳转链接', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('link_url', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'images', 'label': 'Hero 轮播图区块', 'template': 'home/blocks/hero_carousel.html'}), 4: ('wagtail.blocks.CharBlock', (), {'default': '新闻动态'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'NEWS', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.RichTextBlock', (), {}), 8: ('wagtail.blocks.DateBlock', (), {}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('summary', 7), ('date', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 4), ('subtitle', 5), ('news_items', 11), ('view_more_link', 9)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': '媒体报道'}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'MEDIA', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('source', 6), ('title', 6), ('link', 9), ('date', 6)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('title', 13), ('subtitle', 14), ('media_items', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': '活动预告'}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'EVENTS', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('time', 6), ('location', 6)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('title', 18), ('subtitle', 19), ('events', 21), ('view_more_link', 9)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'default': '教育教学'}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'EDUCATION', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('title', 23), ('subtitle', 24), ('content', 7), ('view_more_link', 9)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': '科学研究'}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'RESEARCH', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {}), 30: ('wagtail.blocks.StructBlock', [[('title', 26), ('subtitle', 27), ('research_items', 29), ('view_more_link', 9)]], {})}),
        ),
    ]
