# Generated by Django 6.0.3 on 2026-04-20 06:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('news', 13), ('media', 18), ('events', 23), ('education', 26), ('research', 31)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '轮播图片', 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': '点击图片后的跳转地址', 'label': '跳转链接', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('link_url', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': '幻灯片集合'}), 4: ('wagtail.blocks.StructBlock', [[('slides', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': '新闻动态'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'NEWS', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {}), 9: ('wagtail.blocks.DateBlock', (), {}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 7), ('summary', 8), ('date', 9), ('link', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 5), ('subtitle', 6), ('news_items', 12), ('view_more_link', 10)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'default': '媒体报道'}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'MEDIA', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('source', 7), ('title', 7), ('link', 10), ('date', 7)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('title', 14), ('subtitle', 15), ('media_items', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': '活动预告'}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'EVENTS', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('title', 7), ('description', 8), ('time', 7), ('location', 7)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {}), 23: ('wagtail.blocks.StructBlock', [[('title', 19), ('subtitle', 20), ('events', 22), ('view_more_link', 10)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': '教育教学'}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'EDUCATION', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('title', 24), ('subtitle', 25), ('content', 8), ('view_more_link', 10)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': '科学研究'}), 28: ('wagtail.blocks.CharBlock', (), {'default': 'RESEARCH', 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('title', 7), ('description', 8)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {}), 31: ('wagtail.blocks.StructBlock', [[('title', 27), ('subtitle', 28), ('research_items', 30), ('view_more_link', 10)]], {})}, verbose_name='主页内容区块'),
        ),
    ]
