# Generated by Django 6.0.3 on 2026-04-21 06:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5), ('news', 14), ('media', 19), ('events', 24), ('education', 27), ('research', 32)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '轮播图片', 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': '优先项：点击选择本站内部的具体页面，自动生成防丢链接', 'label': '内部跳转页面', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': '备选项：如果需要跳转到外网（如百度、GitHub），请在此处填写完整 URL', 'label': '外部跳转链接', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('link_page', 1), ('link_external', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': '幻灯片集合'}), 5: ('wagtail.blocks.StructBlock', [[('slides', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': '新闻动态'}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'NEWS', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.DateBlock', (), {}), 11: ('wagtail.blocks.URLBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 8), ('summary', 9), ('date', 10), ('link', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 7), ('news_items', 13), ('view_more_link', 11)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': '媒体报道'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'MEDIA', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('source', 8), ('title', 8), ('link', 11), ('date', 8)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 15), ('subtitle', 16), ('media_items', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'default': '活动预告'}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'EVENTS', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('time', 8), ('location', 8)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {}), 24: ('wagtail.blocks.StructBlock', [[('title', 20), ('subtitle', 21), ('events', 23), ('view_more_link', 11)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': '教育教学'}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'EDUCATION', 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('title', 25), ('subtitle', 26), ('content', 9), ('view_more_link', 11)]], {}), 28: ('wagtail.blocks.CharBlock', (), {'default': '科学研究'}), 29: ('wagtail.blocks.CharBlock', (), {'default': 'RESEARCH', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {}), 32: ('wagtail.blocks.StructBlock', [[('title', 28), ('subtitle', 29), ('research_items', 31), ('view_more_link', 11)]], {})}, verbose_name='主页内容区块'),
        ),
    ]
