# Generated by Django 6.0.3 on 2026-04-24 11:20

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='研究方向综述')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('authors', models.CharField(max_length=500, verbose_name='作者 (用逗号分隔)')),
                ('venue', models.CharField(max_length=255, verbose_name='发表刊物/会议名称')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('pub_type', models.CharField(choices=[('journal', '期刊论文'), ('conf', '会议文章'), ('preprint', '预印本')], default='journal', max_length=20)),
                ('doi', models.URLField(blank=True, verbose_name='DOI/链接')),
                ('bibtex_raw', models.TextField(blank=True, verbose_name='BibTeX 原文 (用于批量导入解析参考)')),
                ('abstract', wagtail.fields.RichTextField(blank=True, verbose_name='摘要')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='research.researchpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='名称')),
                ('role', models.CharField(max_length=100, verbose_name='参与角色')),
                ('status', models.CharField(max_length=100, verbose_name='状态/编号')),
                ('description', wagtail.fields.RichTextField(verbose_name='详细说明')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='research.researchpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
