# Generated by Django 6.0.3 on 2026-04-28 00:45

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='成果摘要'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(max_length=500, verbose_name='作者列表'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='bibtex_raw',
            field=models.TextField(blank=True, default='', null=True, verbose_name='BibTeX 原文 (用于批量导入解析参考)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.URLField(blank=True, default='', verbose_name='外部链接'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_type',
            field=models.CharField(choices=[('journal', '期刊论文'), ('conf', '会议文章'), ('patent', '授权专利')], default='journal', max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=255, verbose_name='成果标题'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='venue',
            field=models.CharField(max_length=255, verbose_name='发表平台/刊物'),
        ),
        migrations.AlterField(
            model_name='researchpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='研究方向综述'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='项目说明'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='role',
            field=models.CharField(max_length=100, verbose_name='职责角色'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(max_length=100, verbose_name='项目编号/状态'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='title',
            field=models.CharField(max_length=255, verbose_name='项目名称'),
        ),
    ]
