# Generated by Django 5.2.12 on 2026-06-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_publication_abstract_alter_publication_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='bibtex_raw',
            field=models.TextField(blank=True, default='', null=True, verbose_name='BibTeX 原文'),
        ),
    ]
