# Generated by Django 6.0.3 on 2026-04-15 11:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='页面简介')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MemberSdPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('academic_status', models.CharField(choices=[('enrolled', '在读'), ('graduated', '已毕业')], default='enrolled', max_length=20, verbose_name='学业状态')),
                ('degree_type', models.CharField(choices=[('master', '硕士'), ('phd', '博士'), ('postdoc', '博士后')], default='master', max_length=20, verbose_name='攻读/获得学位')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('enrollment_year', models.IntegerField(blank=True, help_text='例如：2023', null=True, verbose_name='入学年份')),
                ('dynamic_content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': '章节标题'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': '富文本内容'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '插图'})}, verbose_name='详细信息拓展区')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='成员头像')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MemberTcPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('professional_title', models.CharField(help_text='例如：教授、副教授、特聘研究员等', max_length=100, verbose_name='职称')),
                ('research_direction', models.CharField(help_text='请简要描述您的学术研究领域', max_length=255, verbose_name='主要研究方向')),
                ('dynamic_content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': '章节标题'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': '详细介绍内容'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': '相关插图'})}, verbose_name='其他信息展示区')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='教师头像')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
