# Generated by Django 6.0.3 on 2026-06-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberindexpage',
            name='intro',
        ),
    ]
